# Define open-contest-base container

FROM python:3.8

# Install dependencies.
RUN apt update && apt install -y docker.io psmisc 

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r requirements.txt
